spring:
  datasource:
    name: db_iot
    #dev
    url: jdbc:mysql://localhost:3306/db_iot?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    #dev
    host: localhost
    port: 6379
    password:
    timeout: 10000
    database: 1
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 2
        max-wait: 10000
  cloud:
    consul:
      host: ${service.registry.consul-host}
      port: ${service.registry.consul-port}
      discovery:
        health-check-url: http://${service.registry.expose-host}:${service.registry.expose-port}${server.servlet.context-path}/info
        health-check-interval: 5s
        service-name: ${spring.application.name}
        # 启用服务发现
        enabled: true
        query-passing: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:com/freedougall/demo/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.freedougall.demo.**
  #枚举类型，多个使用分号分隔
  typeEnumsPackage: com.freedougall.demo.enums
  global-config:
    db-config:
      # logic-delete-field: metaLogicFlag
      logic-delete-value: 2
      logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework: info